fixed up recovery.fstab and twrp.flags and modify multidisabler to make it generic

diff --git a/recovery/root/system/bin/multidisabler b/recovery/root/system/bin/multidisabler
--- a/recovery/root/system/bin/multidisabler
+++ b/recovery/root/system/bin/multidisabler
@@ -1,106 +1,92 @@
 #!/system/bin/sh
-#
-# A simple Samsung services disabler by Ian Macdonald.
-#
-# Use this to prime your device after installing TWRP.
+
+# A generic Services disabler for Android 9 and above.
 
 md5() {
-  md5sum -b "$1"
+ md5sum -b "$1"
 }
 
 file_changed() {
-  local file="$1"
-  local old_md5="$2"
-  local new_md5=$( md5 "$file" )
+ local file="$1"
+ local old_md5="$2"
+ local new_md5=$( md5 "$file" )
 
-  if [ $new_md5 != $old_md5 ]; then
+ if [ $new_md5 != $old_md5 ]; then
     echo " -     ...modified."
-  else
+ else
     echo " -     ...unchanged."
-  fi
+ fi
 }
 
 resize_vendor() {
-  local dm_block=$(df -k | cat | grep "/vendor" | cut -d' ' -f1)
+ local dm_block=$(df -k | cat | grep "/vendor" | cut -d' ' -f1)
 
-  echo " - Unmounting /vendor..."
-  umount /vendor
-  echo " - Checking vendor block parition before resizing..."
-  e2fsck -f $dm_block
-  echo " - Resizing the filesystem on $dm_block..."
-  resize2fs $dm_block
-  echo " - Make the partition R/W by unsharing its blocks..."
-  e2fsck -E unshare_blocks $dm_block
-  echo " - Remounting /vendor..."
-  mount /vendor
-  mount -o remount,rw /vendor
+ echo " - Unmounting /vendor..."
+ umount /vendor
+ echo " - Checking vendor block partition before resizing..."
+ e2fsck -f $dm_block
+ echo " - Resizing the filesystem on $dm_block..."
+ resize2fs $dm_block
+ echo " - Make the partition R/W by unsharing its blocks..."
+ e2fsck -E unshare_blocks $dm_block
+ echo " - Remounting /vendor..."
+ mount /vendor
+ mount -o remount,rw /vendor
 }
 
 vendor_free_size_check() {
-  echo " - Checking vendor free size..."
-  if dd if=/dev/zero of=/vendor/test bs=1 count=1 2>/dev/null; then
+ echo " - Checking vendor free size..."
+ if dd if=/dev/zero of=/vendor/test bs=1 count=1 2>/dev/null; then
     echo " -     ...succeeded."
     rm -f /vendor/test
-  else
+ else
     echo " -     ...No free space left on vendor, attempt to resizing vendor..."
     echo " "
     rm -f /vendor/test
     resize_vendor
-  fi
+ fi
 }
 
 disable_fbe() {
-  local md5
-  local i
-  fstab_files=`grep -lr 'fileencryption' vendor/etc`
+ local md5
+ local i
+ fstab_files=`grep -lr 'fileencryption' vendor/etc`
 
-  #
-  # Exynos devices = fstab.exynos*.
-  # MediaTek devices = fstab.mt*.
-  # Snapdragon devices = fstab.qcom, fstab.emmc, fstab.default
-  #
-  for i in $fstab_files; do
+ for i in $fstab_files; do
     if [ -f $i ]; then
       echo " - Disabling file-based encryption (FBE) for /data..."
       echo " -   Found $i."
       md5=$( md5 $i )
-      # This comments out the offending line and adds an edited one.
       sed -i -e 's/^\([^#].*\)fileencryption=[^,]*\(.*\)$/# &\n\1encryptable\2/g' $i
       file_changed $i $md5
     fi
-  done
+ done
 }
 
 disable_fde() {
-  local md5
-  local i
-  fstab_files=`grep -lr 'forceencrypt' vendor/etc`
+ local md5
+ local i
+ fstab_files=`grep -lr 'forceencrypt' vendor/etc`
 
-  #
-  # Exynos devices = fstab.exynos*.
-  # MediaTek devices = fstab.mt*.
-  # Snapdragon devices = fstab.qcom, fstab.emmc, fstab.default
-  #
-  for i in $fstab_files; do
+ for i in $fstab_files; do
     if [ -f $i ]; then
       echo " - Disabling full-disk encryption (FDE) for /data..."
       echo " -   Found $i."
       md5=$( md5 $i )
-      # This comments out the offending line and adds an edited one.
       sed -i -e 's/^\([^#].*\)forceencrypt=[^,]*\(.*\)$/# &\n\1encryptable\2/g' $i
       file_changed $i $md5
     fi
-  done
+ done
 }
 
 disable_recovery_restoration() {
-  local r=recovery-from-boot.p
-  local found
-  local i
+ local r=recovery-from-boot.p
+ local found
+ local i
 
-  echo " - Disabling restoration of stock recovery..."
+ echo " - Disabling restoration of stock recovery..."
 
-  for i in $ANDROID_ROOT $ANDROID_ROOT/system /vendor; do
+ for i in $ANDROID_ROOT $ANDROID_ROOT/system /vendor; do
     if [ -f $i/$r~ ]; then
 	echo " -   ...already disabled."
 	found=true
@@ -121,49 +107,30 @@ disable_recovery_restoration() {
       break
     fi
 
-  done
+ done
 
-  [ -z "$found" ] && echo " -   Found no stock recovery. Pfft."
+ [ -z "$found" ] && echo " -   Couldn't Find stock recovery."
 }
 
 echo " "
-echo "Multi-disabler v3.1 for Samsung devices"
+echo "Multi-disabler v3.1 for Android Devices"
 echo "running Android 9 or later."
-echo "by Ian Macdonald, enhanced by afaneh92"
+echo "Initial script by Ian Macdonald, enhanced by kelexine"
 echo " "
 
 os=$(getprop ro.build.version.release)
 major=${os%%.*}
-bl=$(getprop ro.boot.bootloader)
-dp=$(getprop ro.boot.dynamic_partitions)
 
-# Firmware version starts at either 8th or 9th character, depending on length
-# of bootloader string (12 or 13).
-#
-fw=${bl:$((${#bl} - 4)):4}
-
-# Device is first 5 characters of bootloader string.
-#
-device=${bl:0:$((${#bl} - 8))}
-mft=$(getprop ro.product.manufacturer | tr '[A-Z]' '[a-z]')
-
-if [ "$mft" != samsung ]; then
-  echo " - Device appears not to be made by Samsung."
-  fatal=true
-elif [ -z "$device" ]; then
-  echo " - Could not determine device model."
-  fatal=true
-elif [ $major -lt 9 ]; then
-  echo " - This software is incompatible with Android $major."
-  fatal=true
+if [ $major -lt 9 ]; then
+ echo " - This software is incompatible with Android $major."
+ fatal=true
 fi
 if [ -n "$fatal" ]; then
-  echo " - Installation aborted."
-  echo " "
-  exit 1
+ echo " - Installation aborted."
+ echo " "
+ exit 1
 fi
 
-echo " - Detected a $device device with a $fw bootloader."
 echo " - The environment appears to be Android $major."
 echo " "
 
@@ -172,13 +139,13 @@ mount $ANDROID_ROOT 2>/dev/null
 mount -o remount,rw $ANDROID_ROOT 2>/dev/null
 
 if ! mount | grep $ANDROID_ROOT >/dev/null; then
-  ANDROID_ROOT=/system_root
-  echo " -   Attempt failed. Mounting at $ANDROID_ROOT..."
-  mount -o rw $ANDROID_ROOT
-  if ! mount | grep $ANDROID_ROOT >/dev/null; then
+ ANDROID_ROOT=/system_root
+ echo " -   Attempt failed. Mounting at $ANDROID_ROOT..."
+ mount -o rw $ANDROID_ROOT
+ if ! mount | grep $ANDROID_ROOT >/dev/null; then
     echo " -   Even that attempt failed. Aborting..."
     exit 2
-  fi
+ fi
 fi
 
 echo " - Mounting /vendor..."
@@ -186,8 +153,8 @@ mount /vendor
 mount -o remount,rw /vendor
 
 if ! mount | grep /vendor >/dev/null; then
-  echo " -   Mount failed. Aborting..."
-  exit 3
+ echo " -   Mount failed. Aborting..."
+ exit 3
 fi
 
 vendor_free_size_check
